

GET http://superheroapi.com/api/1267095494123616/search/batman


### User Registration 
POST http://localhost:8000/api/v1/registerlogin
Content-Type: application/json

{
    "fName":"Roshan",
    "lName":"Bhattarai",
    "email":"roshan021@gmail.com",
    "password":"123456789"
}

### User Login 
POST http://localhost:8000/api/v1/registerlogin/login
Content-Type: application/json

{
    "email":"roshanbhattarai021@gmail.com",
    "password": "123456"
}

### Store Favorite Super Hero

POST http://localhost:8000/api/v1/favourite

